### ISSUE TITLE
Incompatible with analyzer 7.0.0 and source_gen 2.0.0

### ISSUE THREAD

**Issue by vanlooverenkoen** [ikbendewilliam/flutter_navigation_generator#35]

**Comment by vanlooverenkoen** [comment]
By downgrading all dev_dependencies to "below analyzer 7 & source_gen 2" it does work

I only needed to set the meta to 1.15.0

```
dev_dependencies:
  build_runner: ^2.4.15
  code_builder: ^4.10.1
  copy_with_extension_gen: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_navigation_generator: ^2.1.0
  hive_ce_generator: ^1.8.0
  injectable_generator: ^2.6.2
  impaktfull_cli: ^0.23.1
  impaktfull_translations: ^0.0.4
  json_serializable: ^6.9.0
  license_generator: ^2.0.0
  retrofit_generator: ^9.1.9

dependency_overrides:
  meta: 1.15.0
```

Dependencies I needed to downgrade:
- json_serializable
- injectable_generator
- hive_ce_generator
- copy_with_extension_gen
